name: NicompterSMP
version: '${version}'
main: de.cool_miner2021.nicomptersmp.NicompterSMP
api-version: '1.20'
load: STARTUP
commands:
  afk:
    description: "Verändert deinen AFK Status"
  ping:
    description: "Zeigt deinen Ping"
  creeper:
    description: "Spielt bei anderen Spielern einen Creeper Prime Sound ab"
  location:
    description: "Gibt die Koordinaten und Welt eines Spielers an"
    permission: "nicomptersmp.location"
